### ISSUE TITLE
RTT usb驱动转换

### ISSUE THREAD

**Issue by linhuikui** [RT-Thread-packages/tinyusb#14]
建议增加一个转换层，以RTT中现有usb设备驱动为基础封装到tinyusb；
这样的话，现有的，已经写好的usb设备驱动，就能很方便的转换到tinyusb中。很多芯片的驱动就不用再写一遍了。

**Comment by tfx2001** [comment]
之前考虑到性能问题，以及 RTT USB 框架的历史遗留问题，就没有采用这个方案。但如果把 CDC 设备注册为 UART 设备，MSC 设备对接到块设备是没问题的。
