### ISSUE TITLE
MDK5 TinyUSB Compile error --c99

### ISSUE THREAD

**Issue by zhenbin-lin** [RT-Thread-packages/tinyusb#26]
### Operating System

Windows 10

### Board

stm32h7-armfly-v7

### Firmware

1. MDK5.36 ArmClang编译器
2. bsp stm32h7-armfly-v7

### What happened ?

不使用 TinyUSB 的时，基于V7开发板的仓库代码编译没有问题，添加了 TinyUSB 后会报下列错误：

![1682326639538](https://user-images.githubusercontent.com/55196104/233948811-b87e91b9-be0a-4571-83ba-c3c6a2c0cf83.jpg)

上面的使用 ArmClang 编译的，改成 ARMCC 进行编译会出现下面的错误，有勾选GNU扩展选项，也配置了CubeMx的USB驱动：

![image](https://user-images.githubusercontent.com/55196104/233949857-f406c70e-08b9-44a7-84b3-095cd1262344.png)
![image](https://user-images.githubusercontent.com/55196104/233949931-92d6df8a-9417-43be-bb91-a6fdb730b875.png)

### How to reproduce ?

1. 使用 stm32h743-armfly-v7 开发板
2. menuconfig 设置使用 TinyUSB 配置 CubeMX 使能USB设备
3. pkgs --update 下载TinyUSB
4. 配置 AC6 或 AC5 + GNU Extensions
5. 问题出现

### Debug Log as txt file

#ifndef RT_CONFIG_H__
#define RT_CONFIG_H__

/* Automatically generated file; DO NOT EDIT. */
/* RT-Thread Configuration */

/* RT-Thread Kernel */

#define RT_NAME_MAX 8
#define RT_ALIGN_SIZE 8
#define RT_THREAD_PRIORITY_32
#define RT_THREAD_PRIORITY_MAX 32
#define RT_TICK_PER_SECOND 1000
#define RT_USING_OVERFLOW_CHECK
#define RT_USING_HOOK
#define RT_HOOK_USING_FUNC_PTR
#define RT_USING_IDLE_HOOK
#define RT_IDLE_HOOK_LIST_SIZE 4
#define IDLE_THREAD_STACK_SIZE 256
#define RT_USING_TIMER_SOFT
#define RT_TIMER_THREAD_PRIO 4
#define RT_TIMER_THREAD_STACK_SIZE 512

/* kservice optimization */

#define RT_KSERVICE_USING_STDLIB
#define RT_DEBUG

/* Inter-Thread communication */

#define RT_USING_SEMAPHORE
#define RT_USING_MUTEX
#define RT_USING_EVENT
#define RT_USING_MAILBOX
#define RT_USING_MESSAGEQUEUE

/* Memory Management */

#define RT_USING_MEMPOOL
#define RT_USING_SMALL_MEM
#define RT_USING_SMALL_MEM_AS_HEAP
#define RT_USING_HEAP

/* Kernel Device Object */

#define RT_USING_DEVICE
#define RT_USING_CONSOLE
#define RT_CONSOLEBUF_SIZE 128
#define RT_CONSOLE_DEVICE_NAME "uart"
#define RT_VER_NUM 0x50001
#define RT_USING_CACHE
#define RT_USING_HW_ATOMIC
#define RT_USING_CPU_FFS
#define ARCH_ARM
#define ARCH_ARM_CORTEX_M
#define ARCH_ARM_CORTEX_M7

/* RT-Thread Components */

#define RT_USING_COMPONENTS_INIT
#define RT_USING_USER_MAIN
#define RT_MAIN_THREAD_STACK_SIZE 2048
#define RT_MAIN_THREAD_PRIORITY 10
#define RT_USING_MSH
#define RT_USING_FINSH
#define FINSH_USING_MSH
#define FINSH_THREAD_NAME "tshell"
#define FINSH_THREAD_PRIORITY 20
#define FINSH_THREAD_STACK_SIZE 4096
#define FINSH_USING_HISTORY
#define FINSH_HISTORY_LINES 5
#define FINSH_USING_SYMTAB
#define FINSH_CMD_SIZE 80
#define MSH_USING_BUILT_IN_COMMANDS
#define FINSH_USING_DESCRIPTION
#define FINSH_ARG_MAX 10

/* DFS: device virtual file system */

#define RT_USING_DFS
#define DFS_USING_POSIX
#define DFS_USING_WORKDIR
#define DFS_FD_MAX 16
#define RT_USING_DFS_V1
#define DFS_FILESYSTEMS_MAX 4
#define DFS_FILESYSTEM_TYPES_MAX 4
#define RT_USING_DFS_DEVFS

/* Device Drivers */

#define RT_USING_DEVICE_IPC
#define RT_UNAMED_PIPE_NUMBER 64
#define RT_USING_SERIAL
#define RT_USING_SERIAL_V1
#define RT_SERIAL_USING_DMA
#define RT_SERIAL_RB_BUFSZ 64
#define RT_USING_PIN

/* Using USB */

#define RT_USING_USB

/* C/C++ and POSIX layer */

#define RT_LIBC_DEFAULT_TIMEZONE 8

/* POSIX (Portable Operating System Interface) layer */

/* Interprocess Communication (IPC) */

/* Socket is in the 'Network' category */

/* Network */

/* Utilities */

/* RT-Thread Utestcases */

/* RT-Thread online packages */

/* IoT - internet of things */

/* Wi-Fi */

/* Marvell WiFi */

/* Wiced WiFi */

/* IoT Cloud */

/* security packages */

/* language packages */

/* JSON: JavaScript Object Notation, a lightweight data-interchange format */

/* XML: Extensible Markup Language */

/* multimedia packages */

/* LVGL: powerful and easy-to-use embedded GUI library */

/* u8g2: a monochrome graphic library */

/* tools packages */

/* system packages */

/* enhanced kernel services */

/* acceleration: Assembly language or algorithmic acceleration packages */

/* CMSIS: ARM Cortex-M Microcontroller Software Interface Standard */

/* Micrium: Micrium software products porting for RT-Thread */

#define PKG_USING_TINYUSB
#define PKG_TINYUSB_STACK_SIZE 2048
#define PKG_TINYUSB_THREAD_PRIORITY 8
#define PKG_TINYUSB_MEM_SECTION ".data"
#define PKG_TINYUSB_MEM_ALIGN 4
#define PKG_TINYUSB_RHPORT_NUM_1
#define PKG_TINYUSB_RHPORT_NUM 0
#define PKG_TINYUSB_FULL_SPEED
#define PKG_TINYUSB_DEVICE_PORT_SPEED 0x00
#define PKG_TINYUSB_DEVICE_ENABLE
#define PKG_TINYUSB_DEVICE_VID 0xCAFE
#define PKG_TINYUSB_DEVICE_PID 0x4000
#define PKG_TINYUSB_DEVICE_MANUFACTURER "TinyUSB"
#define PKG_TINYUSB_DEVICE_PRODUCT "TinyUSB Device"
#define PKG_TINYUSB_EDPT0_SIZE 64
#define PKG_TINYUSB_DEVICE_CURRENT 100
#define PKG_TINYUSB_DEVICE_CDC
#define CFG_TUD_CDC 1
#define PKG_TINYUSB_DEVICE_CDC_STRING "TinyUSB CDC"
#define PKG_TINYUSB_DEVICE_CDC_EPNUM_NOTIF 1
#define PKG_TINYUSB_DEVICE_CDC_EPNUM 2
#define PKG_TINYUSB_DEVICE_CDC_RX_BUFSIZE 64
#define PKG_TINYUSB_DEVICE_CDC_TX_BUFSIZE 64
#define PKG_TINYUSB_DEBUG_NO
#define CFG_TUSB_DEBUG 0
#define PKG_USING_TINYUSB_V01400

/* peripheral libraries and drivers */

/* sensors drivers */

/* touch drivers */

/* Kendryte SDK */

/* AI packages */

/* Signal Processing and Control Algorithm Packages */

/* miscellaneous packages */

/* project laboratory */

/* samples: kernel and components samples */

/* entertainment: terminal games and other interesting software packages */

/* Arduino libraries */

/* Projects */

/* Sensors */

/* Display */

/* Timing */

/* Data Processing */

/* Data Storage */

/* Communication */

/* Device Control */

/* Other */

/* Signal IO */

/* Uncategorized */

#define SOC_FAMILY_STM32
#define SOC_SERIES_STM32H7

/* Hardware Drivers Config */

#define SOC_STM32H743XI

/* Onboard Peripheral Drivers */

/* On-chip Peripheral Drivers */

#define BSP_USING_GPIO
#define BSP_USING_UART
#define BSP_USING_UART1

/* Board extended module Drivers */

#endif

### I have checked existing issues, dicussion and documentation

- [ ] I confirm I have checked existing issues, dicussion and documentation.

**Comment by zhenbin-lin** [comment]
已经自行解决了该问题，需要说明一下，该文件这部分需要修改~ 

![image](https://user-images.githubusercontent.com/55196104/234147217-c32eeab0-87b1-490f-b9b1-96867046513a.png)

**Comment by tfx2001** [comment]
这部分有什么问题呢，如果可以还请提个PR修复一下

**Comment by zhenbin-lin** [comment]
你好，是这样的 tinyusb\rt-thread\tusb_config.h 文件需要使用到 `RT_SECTION` 和 `ALIGN` 两个宏定义
```c
#ifndef CFG_TUSB_MEM_SECTION
#define CFG_TUSB_MEM_SECTION        RT_SECTION(PKG_TINYUSB_MEM_SECTION)
#endif

#ifndef CFG_TUSB_MEM_ALIGN
#define CFG_TUSB_MEM_ALIGN          ALIGN(PKG_TINYUSB_MEM_ALIGN)
#endif

```
我发现它们定义在 components\legacy\rtlegacy.h 文件中，我在生产 KEIL5 工程时，似乎没有看到这个文件被包含进 includes 目录的配置中。
我将 `RT_SECTION` 和 `ALIGN`  改成了 `rt_section` 和 `rt_align` 并且在 tinyusb\rt-thread\tusb_config.h 文件 `#include <rtdef.h>` 解决了这个问题。

我查阅了一下 components\legacy\rtlegacy.h 文件下面的 Scons 脚本 components\legacy\SConscript
```py
from building import *
import os

src = Split('''
ipc/workqueue_legacy.c
''')

cwd = GetCurrentDir()
CPPPATH = [cwd]

if GetDepend('RT_USING_DFS'):
    dfs_cwd = os.path.join(cwd,'dfs')
    CPPPATH += [dfs_cwd]

group = DefineGroup('Legacy', src, depend = ['RT_USING_LEGACY'], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
```
似乎和 `RT_USING_DFS` 这定义有关系，我在 rtconfig.h 文件中找不到这个宏定义，我不知道通过配置哪里来产生这个宏。

**Comment by zhenbin-lin** [comment]
我查阅了一下 components\legacy\rtlegacy.h 文件下面的 Scons 脚本 components\legacy\SConscript
```py
from building import *
import os

src = Split('''
ipc/workqueue_legacy.c
''')

cwd = GetCurrentDir()
CPPPATH = [cwd]

if GetDepend('RT_USING_DFS'):
    dfs_cwd = os.path.join(cwd,'dfs')
    CPPPATH += [dfs_cwd]

group = DefineGroup('Legacy', src, depend = ['RT_USING_LEGACY'], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
```
似乎和 `RT_USING_LEGACY` 这定义有关系，我在 rtconfig.h 文件中找不到这个宏定义，我不知道通过配置哪里来产生这个宏。

**Comment by mr-cn** [comment]
@tfx2001 你好，该问题虽然在0.13.1版本中得到了解决，但是在实际使用中，env会优先使用版本号更大的0.14.0，但是该版本实际落后于0.13.1，不包含这个修复。可能需要更新为0.14.1才能真正使其在RT Thread 5.0正常使用。

UPDATE: 手动指定0.13.1也不包含此补丁，选择latest才解决。

**Comment by tfx2001** [comment]
@mr-cn 我会发布一个 `0.14.1` 修复版本，感谢反馈。

另外使用 `0.13.1` 版本不包含此修复的原因是 RT-Thread [Gitee 镜像](https://gitee.com/RT-Thread-Mirror/tinyusb/tags)同步问题导致，待 `0.14.1` 版本发布后，请优先使用此版本，或通过 `menuconfig -s` 禁用软件包镜像，同时**清除本地软件包缓存**解决。

![image](https://github.com/RT-Thread-packages/tinyusb/assets/19427212/6c83eb31-2385-4faa-9fa8-6b8cfd8d1f8f)

**Comment by tfx2001** [comment]
@mr-cn 修复版本已经发布：https://github.com/RT-Thread/packages/pull/1711 ，可以手动同步本地包索引或者待明天 Gitee 镜像同步后尝试。
